version: "3.8"

services:
  gitlab:
    networks:
      - simen-networks
    build:
      context: ./gitlab
      dockerfile: Dockerfile
    container_name: simen-gitlab
    restart: always
    hostname: git.oubtest.xyz
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'git.oubtest.xyz'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    volumes:
      - './.data/gitlab/config:/etc/gitlab'
      - './.data/gitlab/logs:/var/log/gitlab'
      - './.data/gitlab/data:/var/opt/gitlab'
  nginx: 
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: simen-nginx
    restart: always
    ports:
      - '15580:80'
      - '15581:443'
    volumes:
      - './.data/nginx/conf.d:/etc/nginx/conf.d'
      - './.data/nginx/certs:/etc/nginx/certs'
      - './.data/nginx/html:/usr/share/nginx/html'

networks:
  simen-networks:
    external: true